### ISSUE TITLE
Build error with GHC 8.10.1-rc1

### ISSUE THREAD

**Issue by asr** [danr/geniplate#12]
GHC 8.10.1-rc1 was [announced](https://mail.haskell.org/pipermail/ghc-devs/2020-January/018530.html). Using this version of GHC I got the following error (after bumping the upper version bound for `template-haskell` in `geniplate-mirror.cabal`):

```
$ cabal v1-install
...
Data/Generics/Geniplate.hs:614:43: error:
    • Couldn't match type ‘Exp’ with ‘Maybe Exp’
      Expected type: [Maybe Exp]
        Actual type: [Exp]
    • In the first argument of ‘TupE’, namely ‘(map VarE vs)’
      In the second argument of ‘($)’, namely ‘TupE (map VarE vs)’
      In the expression: LamE (map VarP vs) $ TupE (map VarE vs)
    |
614 |     let tupE = LamE (map VarP vs) $ TupE (map VarE vs)
    |                                           ^^^^^^^^^^^
Failed to install geniplate-mirror-0.7.6
```

Blocking https://github.com/agda/agda/issues/4242

**Comment by L-TChen** [comment]
Given the [changelog](https://hackage.haskell.org/package/template-haskell-2.15.0.0/changelog) of Template Haskell, there is a non-API-breaking functions available.

I will work on this soon.

**Comment by L-TChen** [comment]
Okay, I will see what I can do. Given the [changelog](https://gitlab.haskell.org/ghc/ghc/blob/4898df1cc25132dc9e2599d4fa4e1bbc9423cda5/libraries/template-haskell/changelog.md), there are some API-breaking changes, so it requires some work to do.

**Comment by L-TChen** [comment]
`TupE` handles tuple sections, so its type is changed from `[Exp] -> Exp` to `[Maybe Exp] -> Exp`. 

@asr, please check if d0bb4c711af4104ef07bd073982713e0355d6777  solve the issue you have. 

An updated version of `geneplate-mirror` will not be uploaded to Hackage until GHC 8.10.1 is officially released.

**Comment by asr** [comment]
@L-TChen, it worked. Thanks!

**Comment by asr** [comment]
> An updated version of `geneplate-mirror` will not be uploaded to Hackage until GHC 8.10.1 is officially released.

@L-TChen, GHC 8.10.1 was [released](https://mail.haskell.org/pipermail/ghc-devs/2020-March/018729.html). Please upload a new version on Hackage.

**Comment by L-TChen** [comment]
Thanks for the update. I currently don’t have a laptop till April. Please wait for a moment.

**Comment by L-TChen** [comment]
All done! See http://hackage.haskell.org/package/geniplate-mirror-0.7.7
