### ISSUE TITLE
Missing support for template-haskell-2.11.*

### ISSUE THREAD

**Issue by asr** [danr/geniplate#2]
template-haskell-2.11.\* will be shipped with GHC 8. Please add support for this version of template-haskell.

**Comment by danr** [comment]
Did you check if it builds? I don't have a copy of GHC 8 around.

**Comment by asr** [comment]
> Did you check if it builds?

It is necessary some changes. I'll send a pull request later.

**Comment by asr** [comment]
Could you release a new version on Hackage, please.

**Comment by asr** [comment]
Thanks for releasing.
